version: "3.8"

services:
  backend:
    build: ./backend
    container_name: e2e-project-backend-container
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: e2e-project-frontend-container
    ports:
      - "5173:80"
    restart: unless-stopped
    depends_on:
      - backend
