apiVersion: v1
kind: Service
metadata:
  name: e2e-project-backend-service
spec:
  type: ClusterIP
  selector:
    app: e2e-project-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
