name: Build and Push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: praveenuppar/e2e-project-backend-image:v1

      - name: Build and push Docker frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: praveenuppar/e2e-project-frontend-image:v1
